management:
  security.enabled: false
  endpoints:
    web.exposure.include: health,info,env,mappings

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa

common:
  trigger-route: "direct:start"

analytics:
  trigger-route: "direct:analytics-trigger"
  read-file-uri: "file:src/test/resources?noop=true&fileName=input.csv"
  insert-db-uri: "sql:INSERT INTO users (id,used_directory_search_last_access_timestamp) VALUES (:#id,:#used_directory_search_last_access_timestamp)"


api:
  trigger-route:   "direct:api-trigger"
  access-token-uri: "https4://d-apigw.qhrtech.com/auth/oauth/v2/token"
  api-endpoint:    "http4://localhost:8082/users"
  insert-user-uri: "sql:INSERT INTO users_sf (id, creation_time, last_update_time) VALUES (:#id, :#creationTime, :#lastUpdateTime)"


extraction:
  trigger-route: "direct:extraction-trigger"
  read-db-uri:   "sql:SELECT a.id,b.creation_time,b.last_update_time, a.used_directory_search_last_access_timestamp  from users a join  users_sf b on a.id = b.id"
  create-file-uri: "file:src/data/out?fileName=MyFile.csv&fileExist=Append"