management:
  security.enabled: false
  endpoints:
    web.exposure.include: health,info,env,mappings

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa

common:
  trigger-route: "direct:start"
  enable-analytics-route: "false"
  enable-api-route: "true"


analytics:
  trigger-route: "direct:analytics-trigger"
  read-file-uri: "file:src/test/resources?noop=true&fileName=input.csv"
  insert-db-uri: "sql:INSERT INTO users (id,used_directory_search_last_access_timestamp) VALUES (:#id,:#used_directory_search_last_access_timestamp)"


api:
  trigger-route:   "direct:api-trigger"
  access-token-uri: "https4://d-apigw.qhrtech.com/auth/oauth/v2/token"
  api-endpoint:    "http4://localhost:8082/users"
  insert-user-uri: "sql:INSERT INTO users_sf (id, creation_time, last_update_time) VALUES (:#id, :#creationTime, :#lastUpdateTime)"
  content-type: "application/x-www-form-urlencoded"
  auth-api-body: "grant_type=client_credentials&scope=idp.link.okta_pcid_report"
  cache-control: "no-cache"
  client-id: "80af2d32-6ab8-4ffc-a428-ece67b793916"
  secret-key: "ba75d1f2-8bb6-41f0-b2e3-2884c5fd38aa"


extraction:
  trigger-route: "direct:extraction-trigger"
  read-db-uri:   "sql:SELECT id, creation_time, last_update_time from users_sf"
  create-file-uri: "file:src/data/out?fileName=Extracted_User.csv&fileExist=Append"