CREATE TABLE users (
id VARCHAR(255),
email_address VARCHAR(255),
preferred_name VARCHAR(255),
address VARCHAR(255),
city VARCHAR(255),
province VARCHAR(255),
postal_code VARCHAR(255),
drx_status VARCHAR(255),
drx_enrollment_timestamp VARCHAR(255),
drx_verified_user_flag VARCHAR(255),
drx_verified_user_timestamp VARCHAR(255),
drx_language_prefence VARCHAR(255),
drx_primary_store VARCHAR(255),
drx_home_store_address VARCHAR(255),
drx_city VARCHAR(255),
drx_province VARCHAR(255),
drx_postal_code VARCHAR(255),
drx_receiveEmailPickupNotification VARCHAR(255),
drx_receiveEmailFillNotification VARCHAR(255),
drx_globalAutoFill VARCHAR(255),
drx_receive_marketing_email_flag VARCHAR(255),
drx_receive_marketing_email_update_timestamp VARCHAR(255),
drx_used_web_flag VARCHAR(255),
drx_used_web_last_access_timestamp VARCHAR(255),
drx_used_web_count VARCHAR(255),
program_status VARCHAR(255),
program_enrollment_timestamp VARCHAR(255),
program_last_accessed_timestamp VARCHAR(255),
program_accessed_count VARCHAR(255),
used_virtual_care_flag VARCHAR(255),
used_virtual_care_count VARCHAR(255),
used_virtual_care_last_access_timestamp VARCHAR(255),
used_directory_search_flag VARCHAR(255),
used_directory_search_count VARCHAR(255),
used_directory_search_last_access_timestamp VARCHAR(255)
);

CREATE TABLE users_sf (
id VARCHAR(255),
creation_time VARCHAR(255),
last_update_time VARCHAR(255)
);